name: Deploy static content to Pages

on:
  push:
    branches: ['main']
    paths:
      - frontend/**
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Add a new step to change to the frontend directory
      - name: Change to frontend dir
        run: |
          cd frontend
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          # Add the working-directory parameter
          working-directory: ./frontend
      - name: Install dependencies
        run: npm ci
        # Add the working-directory parameter
        working-directory: ./frontend
      - name: Build
        run: npm run build
        # Add the working-directory parameter
        working-directory: ./frontend
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload dist folder
          path: './frontend/dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
